# Start with a .NET 8 SDK on existing OS
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy over source code including Models
COPY RecipeManager.API/ /app/RecipeManager.API
COPY RecipeManager.Data/ /app/RecipeManager.Data
COPY RecipeManager.Models/ /app/RecipeManager.Models 
COPY RecipeManager.Tests/ /app/RecipeManager.Tests

# Restore dependencies for all projects
RUN dotnet restore RecipeManager.API/RecipeManager.API.csproj

# Run and publish .NET artifact
RUN dotnet publish RecipeManager.API/RecipeManager.API.csproj -c Release -o dist 

# Make new layer 
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS run 
#layers
# Ask ASP.NET to serve over port 80
ENV ASPNETCORE_URLS=http://*:80

WORKDIR /app

# Copy over artifacts from build layer
COPY --from=build /app/dist .

# What to do when docker run is called
CMD [ "dotnet", "RecipeManager.API.dll" ]
#run 