name: CI/CD for Backend with Docker
# test
# Define the events that will trigger this workflow
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    paths:
      - Backend/**  # Trigger only if there are changes in the Backend directory
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch
    paths:
      - Backend/**  # Trigger only if there are changes in the Backend directory

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Step to check out code from the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for building multi-platform images

      - name: Build Docker Image
        run: |
          # Build the Docker image and tag it with the specified name and version
          docker build -t koalacoder/recipe:0.0.4 -f Backend/dockerfile Backend/
          # Ensure that we are using the correct path for both Dockerfile and context

      - name: Log in to Docker Hub (or another registry)
        uses: docker/login-action@v1  # Log in to Docker Hub or your container registry
        with:
            registry: https://index.docker.io/v1/
            username: ${{ secrets.DOCKER_USERNAME }}  # Use your Docker Hub username from secrets
            password: ${{ secrets.DOCKER_PASSWORD }}  # Use your Docker Hub password from secrets

      - name: Push Docker Image
        run: |
              docker push koalacoder/recipe:0.0.4

  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for deployment job
    needs: build  # Ensure this job runs after the build job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checkout code again for deployment step

      - name: Check Secrets (Debug)
        run: |
          echo "Username: ${{ secrets.DOCKER_USERNAME}}"
          echo "Password: ${{ secrets.DOCKER_PASSWORD  }}"
      
      
#changes were made 
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'JDAnderson'  # Ensure this matches your Azure Web App name
            slot-name: 'production'  # Specify the deployment slot if applicable
            publish-profile: ${{ secrets.AZURE_PUBLISHPROFILE }}  # Simplified secret reference
            images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/recipe:0.0.4'
