name: CI/CD for Backend with Docker

# Define the events that will trigger this workflow
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Step to check out the code from the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for building multi-platform images

      - name: Build Docker Image
        run: |
          # Build the Docker image and tag it with the specified name and version
          docker build -t koalacoder/recipe:0.0.4 -f Backend/dockerfile Backend/  # Specify Dockerfile path and build context

      - name: Run Tests (Optional)
        run: |
          # Run tests inside the Docker container
          docker run --rm koalacoder/recipe:0.0.4 dotnet test RecipeManager.Tests/RecipeManager.Tests.csproj
      
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for deployment job
    needs: build  # Ensure this job runs after the build job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checkout code again for deployment step
      
      - name: Log in to Docker Hub (or another registry)
        uses: docker/login-action@v1  # Log in to Docker Hub or your container registry
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use your Docker Hub username from secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use your Docker Hub password from secrets

      - name: Push Docker Image to Registry
        run: |
          # Push the built image to Docker Hub or another container registry
          docker push koalacoder/recipe:0.0.4  # Adjust this line if using a different image name or tag
