name: CI/CD for Backend with Docker

# Define the events that will trigger this workflow
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    paths:
      - Backend/**  # Trigger only if there are changes in the Backend directory
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch
    paths:
      - Backend/**  # Trigger only if there are changes in the Backend directory

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Step to check out code from the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for building multi-platform images

      - name: Build Docker Image
        run: |
          # Build the Docker image and tag it with the specified name and version
          docker build -t koalacoder/recipe:0.0.4 -f Backend/dockerfile Backend/
          # Ensure that we are using the correct path for both Dockerfile and context

      - name: Log in to Docker Hub (or another registry)
        uses: docker/login-action@v1  # Log in to Docker Hub or your container registry
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}  # Use your Docker Hub username from secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use your Docker Hub password from secrets

      - name: Push Docker Image
        run: |
          docker push koalacoder/recipe:0.0.4

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check Secrets (Debug)
        run: |
          echo "Username: ${{ secrets.DOCKER_USERNAME}}"
          echo "Password: ${{ secrets.DOCKER_PASSWORD  }}"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'JDAnderson'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/koalacoder/recipe:0.0.4'